exceptions = {
    'the <CAT> re': 'there',
    'he <CAT> re': 'here',
    'so <CAT> me': 'some',
    'hi <CAT> s': 'his',
    'th <CAT> ing': 'thing',
    're <CAT> ally': 'really',
    'fin <CAT> ally': 'finally',
    'basic <CAT> ally': 'basically',
    'th <CAT> rough': 'through',
    'th <CAT> ought': 'thought',
    'be <CAT> lie <CAT> ve': 'believe',
    'bet <CAT> we <CAT> en': 'between',
    'ca <CAT> tego <CAT> ry': 'catrgory',
    'hum <CAT> an': 'human',
    'sma <CAT> ll': 'small',
    'he <CAT> ad': 'head',
    'co <CAT> re': 'core',
    'co <CAT> me': 'come',
    'th <CAT> en': 'then',
    'on <CAT> ly': 'only',
    'th <CAT> is': 'this',
    'th <CAT> at': 'that',
    'th <CAT> ey': 'they',
    'ha <CAT> ve': 'have',
    'we <CAT> re': 'were',
    're <CAT> ed': 'read',
    'un <CAT> it': 'unit',
    'form <CAT> at': 'format',
    'lat <CAT> er': 'late <CAT> er',
    'us <CAT> ed': 'use <CAT> ed',
    'th <CAT> in <CAT> k': 'think ',
    "n ' t": " not"
}
